#16 about block no2
front-end-by-rimantas/33-grupe-portfolio-neuron pull request #67
Opened 2022-02-18 01:16 UTC by PauliusZiedelis

about block 2 full task
youtube video sill show errors (cookies and js from youtube)

2022-02-18 11:25 UTC, lauraMeiz approved these changes

2022-02-19 11:50 UTC, noravis requested changes
Small and medium ekranuose, kur tekstas palenda po paveikslėliu, antraštės dydis yra per didelis ir o paragrafo yra per mažas ir negerai žiūrisi (žr. originalą). 
Large ekrane learn more mygtukas hoverinant mirksi. Tarsi labai greitai išnyksta ir vėl atsiranta. Mažinant ekraną problema dingsta. Reikėtų pažiūrėti šitus dalykus.

2022-02-19 12:34 UTC, PauliusZiedelis commented
fixing text size and button

2022-02-19 12:34 UTC, closed without merging

2022-02-19 12:45 UTC, noravis commented
aš manau, kad originale jis ne mirksi, o keičiasi opacity. Nu pažiūrėsim eigoj.